### PR TITLE
Recursive mkdir just makes the same directory repeatedly

### PR DESCRIPTION
**Pull request by thebwt**

### CODE REVIEW

**Comment by thebwt** [comment]
I'm very new to all of this, but we need to get a copy of currPath at .then()'s first call time. Not currPath when everything is ready to be run.

**Comment by thebwt** [comment]
I was able to make some progress on this in the raw rendered javascript.

            var addMkdirJob = function (newPath) {
              return _this.mkdir(newPath, false, attributes)
            }
            result = result.then(addMkdirJob(currPath))["catch"](function(err) {
              if (err.code !== ERROR_CODES.FAILURE && err.code !== ERROR_CODES.FILE_ALREADY_EXISTS) {
                throw err;
              }
            });

That allows the path to get set in the correct scope.

**Comment by thebwt** [comment]
With that, the fix should be implemented.

**Comment by zacronos** [comment]
Thanks for the contribution!

**Comment by thebwt** [comment]
No problemo, was a good intro to javascript/coffee script

**Pull request merged**
